require "Items/ProceduralDistributions"
-- V102Tire2
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.V102Tire2");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.6);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.V102Tire2");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.6);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.V102Tire2");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.6);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.V102Tire2");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.6);