-- Disabled: this file used to register a second OnClientCommand handler on top of vanilla,
-- which duplicated vehicle.installPart / uninstallPart / repairEngine and caused item dupes.
-- Custom logic (repair admin check, remove/rmove, repairEngine server item remove) moved to:
-- media/lua/server/Vehicles/VehicleCommands.lua (proper vanilla path override).
